### PR TITLE
Check whether a value is nil that may be set nil in parsing IRC message'...

### PR DESCRIPTION
**Pull request by toqoz**
``` ruby
join_msg = ":example!~example@example.com JOIN :#channel\r\n"
Zircon::Message::Patterns::MESSAGE_PATTERN.match(join_msg)[3..-1]
=> ["", "#channel", nil, nil]
```

Error will occur in lib/zircon/message.rb:43.

```
undefined method `empty?' for nil:NilClass (NoMethodError)
```

https://github.com/r7kamura/zircon/blob/master/lib/zircon/message.rb#L43

I don't understand perfectly Zircon::Message::Patterns::MESSAGE_PATTERN yet. (My knowledge of RegExp is a little...)
So I don't have self-confidence whether this approach is good...

### CODE REVIEW

**Comment by toqoz** [comment]
Should I think this has been declined :eyes: ?

**Comment by r7kamura** [comment]
I'm sorry to my slow reaction, but I'm still thinking this change is correct or not in this 6 days

**Comment by toqoz** [comment]
oh, sorry. If so, there is no problem. I just worried about whether you have forgotten to decline.

**Comment by r7kamura** [comment]
@ToQoz I'm sorry to be late. I have merged, thx!

**Comment by toqoz** [comment]
Thanks!

**Pull request merged**
