### PR TITLE
Support SSL connection

### PR DESCRIPTION
**Pull request by tomohiro**
I've added new option for SSL connection.

SSL connection example:

``` ruby
client = Zircon.new(
  :server   => "chat.freenode.net",
  :port     => "6697",
  :channel  => "#zircon",
  :username => "zircon",
  :use_ssl  => true
)
client.run!
```

### CODE REVIEW

**Comment by r7kamura** [comment]
How can I try to test if the `use_ssl` option works correctly?

**Comment by tomohiro** [comment]
Sorry for this patches not contain test.
I've tested connect to Freenode SSL ports(6697, 7000, 7070).

**Comment by r7kamura** [comment]
It's okay if you've tested :ok_woman:  Thanks for your Pull Request!

**Comment by r7kamura** [comment]
Just shipped v0.0.7 :ship:

**Comment by tomohiro** [comment]
Thank you! :smile:

**Pull request merged**
